### ISSUE TITLE
Opening emote menu crashes.

### ISSUE THREAD

**Issue by mmattbtw** [HiDeoo/YaTA#47]
**To Reproduce**

1. Click the emote menu.
2. Either wait / click the BTTV Icon.
3. Crash

**Error**

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at uc (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:797855)
    at hs (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:811096)
    at t.unstable_runWithPriority (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:831852)
    at Uo (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:755980)
    at ps (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:808954)
    at Jc (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:805085)
    at https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:756271
    at t.unstable_runWithPriority (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:831852)
    at Uo (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:755980)
    at qo (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:756216)
    at Ko (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:756151)
    at N (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:825818)
    at V (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:713013)
    at Zt (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:734599)
    at Qt (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:733816)
    at t.unstable_runWithPriority (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:831852)
    at Xt (https://yata.now.sh/static/js/2.4342c5d4.chunk.js:2:733686)
```

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.14.0
| Browser          | Chrome 84.0.4147.89
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
Hi, thanks for the report.

Does this happen on all channels or only a specific one? If only one, would it be possible to share the channel as I tested in a few channels using Bttv but didn't manage to repro.

**Comment by mmattbtw** [comment]
It happened in my channel, mmattbtw

**Comment by HiDeoo** [comment]
Hmmm, interesting, even in your channel I cannot repro. I'll investigate and try to find a repro based on the error you provided 👍

**Comment by mmattbtw** [comment]
Works fine now, I believe the problem is the "Global Twitch Emotes" extension.

Yep that's the problem, if you have this extension installed, https://chrome.google.com/webstore/detail/global-twitch-emotes/pgniedifoejifjkndekolimjeclnokkb?hl=en, the emote menu crashes.

issue closed.

**Comment by HiDeoo** [comment]
Thanks for the investigations and follow-up. From a quick read of the description of the extension, I can see why this could lead to this error if they modify some DOM nodes to do some replacements, which the app do not expect.

I'll still check when I have some free time if I can somehow prevent this.
