### ISSUE TITLE
Error on Clicking Channel

### ISSUE THREAD

**Issue by c17r** [HiDeoo/YaTA#64]
**To Reproduce**

1. Opened the window as usual using my bookmark to create the most compact window I can: javascript:(function(){window.open('https://yata.now.sh', '_blank', 'menubar=0,toolbar=0,location=0,status=0,scrollbars=0,noopener')})();
2. List of channels came up as normal. I clicked on "CohhCarnage"
3. *BAM* error
4. Used the "Report & Reload" button, and the channel came up fine.

**Error**

```
Error: Not connected to server.
    at n.<anonymous> (https://yata.now.sh/static/js/main.fd31b0f2.chunk.js:1:379240)
    at s (https://yata.now.sh/static/js/2.7b7c21e0.chunk.js:2:1316205)
    at Generator._invoke (https://yata.now.sh/static/js/2.7b7c21e0.chunk.js:2:1315958)
    at Generator.forEach.e.<computed> [as throw] (https://yata.now.sh/static/js/2.7b7c21e0.chunk.js:2:1316562)
    at r (https://yata.now.sh/static/js/2.7b7c21e0.chunk.js:2:89152)
    at s (https://yata.now.sh/static/js/2.7b7c21e0.chunk.js:2:89391)
```

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.15.0
| Browser          | Chrome 88.0.4324.182
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
Hi, thanks for the report.

Tried to repro for a bit but with no luck so far. At first sight, it looks like a random network issue (not sure on which end tho). I'll keep an eye on this to see if this happens to me too or if I get some additional reports and then decide if something needs to be done or not.
